name: worldmusic
version: '1.0-SNAPSHOT'
main: fr.themdeil.worldmusic.Worldmusic
api-version: '1.20'
commands:
  worldmusic:
    description: "Play World Music"
    permission: worldmusic.play
    aliases: wm
    